Removed 'using System.Linq;' as it was unused and for some reason causing: TestSelectQueryDB.cs(27,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference ?)